# Generated by Django 3.2.4 on 2021-06-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('area', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('email', models.EmailField(default='', max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
